spring:
  application:
    name: reclamations-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/restaurantDB

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=100,expireAfterAccess=3600s

server:
  port: 8082
  servlet:
    context-path: /

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    hostname: localhost

stripe:
  apiKey: sk_test_51OooujHlBP4i2gKTlAvEzrOf78uJjXHKB12LTbjTQup1KeJtZqBUIqIT7QKfxLWKzSEFt6U7ryWbFpsCg7DkceXs00v9eezVoN

logging:
  level:
    org.springframework.mail: DEBUG
    com.sun.mail: DEBUG
    javax.mail: DEBUG
    com.restaurant.reclamations: DEBUG